### ISSUE TITLE
wifi sta scan broken

### ISSUE THREAD

**Issue by elapt1c** [rbenrax/upyOS#1]
/ $: wifi sta scan
Error executing wifi
Traceback (most recent call last):
  File "/lib/proc.py", line 55, in run
  File "/bin/wifi.py", line 166, in __main__
  File "/bin/wifi.py", line 64, in psts
KeyError: 0
/ $:

this happens a lot. also, is there a basic interpreter that works with micropython? is there any games i can play on this?

im using rpi pico w

**Comment by rbenrax** [comment]
Thanks for the feedback, I will try to correct the problem, but I do
not have a micro w rpi for testing.

what version of micorpython do you use?, try another version.


I think there are several Basic interpreters for micropython.

**Comment by elapt1c** [comment]
I got retiredwizard's fork of PyBasic running. i can't switch versions of microptyhon because i'm scared of my configs and edits to the filesystem. like in main, i have `input("Press [ENTER] to start.")` there before the booting code to make it feel nicer. also when you press enter on the prompt, i made it do PWM stuff to go "boop beep" when you press enter to make it feel nicer. for a lot of programs i use pin3 for buzzer/speaker in that and also i user some programs from PyBasic (made by RetiredWiszard also) which do some sound stuff. it needs some more functionalities like some TUI games. I have a bouncing ball (game?) that just simulates a ball bouncing around a box like the DVD screensaver code (this is 100% functional and the full code):
```x=y=d=e=1

while 1:
  m=[[' 'for i in' '*80]for j in' '*24];x+=d;y+=e;m[y][x]='⬤';
  if x%79<1:d=-d
  if y%23<1:e=-e  
  print("\033[2J")
  # Add top and bottom borders with hashtags
  print("█" * 85)
  for r in m:
    print('██' + ''.join(r) + ' ██')
  # Add top and bottom borders with hashtags
  print("█" * 85)```

**Comment by elapt1c** [comment]
![image](https://github.com/rbenrax/upyOS/assets/79235234/3e721138-24b9-43d7-b5dd-743e3a915eb2) (this is ball.py ^)
main.py (altered):
```
import machine
import time
import kernel

# Define buzzer pin (replace with another pin if needed)
buzzer_pin = machine.Pin(3, machine.Pin.OUT)

# Define note frequencies (adjust as needed)
NOTES = {
  'C': 261,
  'D': 294,
  'E': 329,
  'F': 349,
  'G': 392,
  'A': 440,
  'B': 494
}

def play_sound(note, duration=0.1):
  """Plays a single note using PWM."""
  if note in NOTES:
    # Create a PWM object for the buzzer pin
    buzzer = machine.PWM(buzzer_pin)
    buzzer.freq(NOTES[note])  # Set frequency based on note
    buzzer.duty_u16(5000)  # Adjust duty cycle for volume (optional)
    time.sleep(duration)  # Play for specified duration
    buzzer.duty_u16(0)  # Stop sound
  else:
    # Handle silence (optional: add a short delay)
    time.sleep(duration/10)  # Adjust delay for silence

def main():
  print("\033[2J")  # Clear screen
  input("Press [ENTER] to Start. ")

  # Play boop sound (adjust note as needed)
  play_sound("D", 0.1)

  # Play beep sound
  play_sound("G", 0.2)

  # Launch upyOS (assuming kernel is defined elsewhere)
  upyos = kernel.upyOS("")  # Boot_args: -r

# Run the main function directly
main()

**Comment by elapt1c** [comment]
also i'm having issues with killing other cores. for example, i'm running RetiredWizard's buzz.py program on it in core 2 `buzz &` and cannot make it stop without running `reset`

**Comment by rbenrax** [comment]
In upyOS programs must implement a main function like this:

def __main__(args):
   ...

If you want stop a batch process you must declare the following variable
after imports

# proc ref passed in call
proc=None

And in the main loop of program do a controlled exit of the program, is not
a good idea that a OS stop a thread or process, never could do in a
controlled basis.

# Controlling exit and hold of a batch process

    while True:
        if proc.sts=="S":break
        if proc.sts=="H":
            utime.sleep(1)
            continue
        ... rest of the procedure

Then lauch with $, ps to see process and kill, killall or hold to control
your program

You can see several usage examples in the bin directory
use upyOS command
/bin $ grep proc=

I hope you find it useful
